spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8081/
          predicates:
            - Path=/tourism/api/v1/users/**
        - id: r2
          uri: http://localhost:8082/
          predicates:
            - Path=/tourism/api/v1/regions/**


  application:
    name: gateway-service
server:
  port: 8888